// config
export const CONFIG_CLONES = 2;
export const CONFIG_CHECK_TIMEOUT = 1000;

// actions
export const REMOVED_CARDS = 'REMOVED_CARDS';
export const RESET_CARDS = 'RESET_CARDS';
export const RESET_PICKS = 'RESET_PICKS';
export const TOGGLED_CARD = 'TOGGLED_CARD';
export const TOGGLED_CARD_HIGHLIGHT = 'TOGGLED_CARD_HIGHLIGHT';
export const TOGGLED_PICK_AVAILABLE = 'TOGGLED_PICK_AVAILABLE';
